// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: contract/token_collector.proto

package token_collector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *InsertTokenRequest) Reset() {
	*x = InsertTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_token_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTokenRequest) ProtoMessage() {}

func (x *InsertTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_token_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTokenRequest.ProtoReflect.Descriptor instead.
func (*InsertTokenRequest) Descriptor() ([]byte, []int) {
	return file_contract_token_collector_proto_rawDescGZIP(), []int{0}
}

func (x *InsertTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBucketInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetBucketInformationRequest) Reset() {
	*x = GetBucketInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_token_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBucketInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketInformationRequest) ProtoMessage() {}

func (x *GetBucketInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_token_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketInformationRequest.ProtoReflect.Descriptor instead.
func (*GetBucketInformationRequest) Descriptor() ([]byte, []int) {
	return file_contract_token_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetBucketInformationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBucketInformationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens        float32 `protobuf:"fixed32,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	LastAccess    int64   `protobuf:"varint,2,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	TotalAttempts int64   `protobuf:"varint,3,opt,name=totalAttempts,proto3" json:"totalAttempts,omitempty"`
}

func (x *GetBucketInformationReply) Reset() {
	*x = GetBucketInformationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_token_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBucketInformationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketInformationReply) ProtoMessage() {}

func (x *GetBucketInformationReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_token_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketInformationReply.ProtoReflect.Descriptor instead.
func (*GetBucketInformationReply) Descriptor() ([]byte, []int) {
	return file_contract_token_collector_proto_rawDescGZIP(), []int{2}
}

func (x *GetBucketInformationReply) GetTokens() float32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *GetBucketInformationReply) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

func (x *GetBucketInformationReply) GetTotalAttempts() int64 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

type InsertTokenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *InsertTokenReply) Reset() {
	*x = InsertTokenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_token_collector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTokenReply) ProtoMessage() {}

func (x *InsertTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_token_collector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTokenReply.ProtoReflect.Descriptor instead.
func (*InsertTokenReply) Descriptor() ([]byte, []int) {
	return file_contract_token_collector_proto_rawDescGZIP(), []int{3}
}

func (x *InsertTokenReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_contract_token_collector_proto protoreflect.FileDescriptor

var file_contract_token_collector_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2c, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73,
	0x22, 0x2c, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x9d,
	0x01, 0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x37, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x13, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x47,
	0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x75,
	0x6e, 0x6f, 0x65, 0x64, 0x75, 0x61, 0x72, 0x64, 0x6f, 0x64, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2d, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_token_collector_proto_rawDescOnce sync.Once
	file_contract_token_collector_proto_rawDescData = file_contract_token_collector_proto_rawDesc
)

func file_contract_token_collector_proto_rawDescGZIP() []byte {
	file_contract_token_collector_proto_rawDescOnce.Do(func() {
		file_contract_token_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_token_collector_proto_rawDescData)
	})
	return file_contract_token_collector_proto_rawDescData
}

var file_contract_token_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contract_token_collector_proto_goTypes = []interface{}{
	(*InsertTokenRequest)(nil),          // 0: InsertTokenRequest
	(*GetBucketInformationRequest)(nil), // 1: GetBucketInformationRequest
	(*GetBucketInformationReply)(nil),   // 2: GetBucketInformationReply
	(*InsertTokenReply)(nil),            // 3: InsertTokenReply
}
var file_contract_token_collector_proto_depIdxs = []int32{
	0, // 0: TokenCollector.InsertToken:input_type -> InsertTokenRequest
	1, // 1: TokenCollector.GetBucketInformation:input_type -> GetBucketInformationRequest
	3, // 2: TokenCollector.InsertToken:output_type -> InsertTokenReply
	2, // 3: TokenCollector.GetBucketInformation:output_type -> GetBucketInformationReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_token_collector_proto_init() }
func file_contract_token_collector_proto_init() {
	if File_contract_token_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_token_collector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_token_collector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBucketInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_token_collector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBucketInformationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_token_collector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTokenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_token_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_token_collector_proto_goTypes,
		DependencyIndexes: file_contract_token_collector_proto_depIdxs,
		MessageInfos:      file_contract_token_collector_proto_msgTypes,
	}.Build()
	File_contract_token_collector_proto = out.File
	file_contract_token_collector_proto_rawDesc = nil
	file_contract_token_collector_proto_goTypes = nil
	file_contract_token_collector_proto_depIdxs = nil
}
